# Generated by Django 5.2.17 on 2026-09-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl'), ('not_specified', 'Not specified')], default='', max_length=16),
        ),
    ]
