# Generated by Django 5.2.17 on 2026-09-24 20:50

from django.db import migrations, models


def populate_audit_metadata(apps, schema_editor):
    AuditEvent = apps.get_model("school", "PortalAuditEvent")
    failures = {"login_failure", "registration_status_failure", "role_access_denied", "locked_out", "ip_rate_limited"}
    for event in AuditEvent.objects.all().iterator():
        if event.action.startswith(("login_", "registration_status_")):
            event.factor = "password"
        elif event.action.startswith("logout_"):
            event.factor = "session"
        else:
            event.factor = "access"
        event.outcome = (
            "failure"
            if event.action in failures or event.action.endswith(("_failure", "_denied"))
            else "success"
        )
        event.save(update_fields=("factor", "outcome"))


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_course_teacher_portalauditevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalauditevent',
            name='auth_mode',
            field=models.CharField(choices=[('password', 'Password only'), ('otp', 'Password + OTP'), ('otp_email', 'Password + OTP + email OTP')], default='password', max_length=16),
        ),
        migrations.AddField(
            model_name='portalauditevent',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalauditevent',
            name='factor',
            field=models.CharField(choices=[('password', 'Password'), ('mobile_otp', 'Mobile OTP'), ('email_otp', 'Email OTP'), ('session', 'Session'), ('access', 'Access control')], default='access', max_length=16),
        ),
        migrations.AddField(
            model_name='portalauditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalauditevent',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=8),
        ),
        migrations.AddField(
            model_name='portalauditevent',
            name='session_hint',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.RunPython(populate_audit_metadata, migrations.RunPython.noop),
    ]
