# Generated by Django 5.2.17 on 2026-09-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPortalAuditEvent',
            fields=[
            ],
            options={
                'verbose_name': 'student audit event',
                'verbose_name_plural': 'student audit events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.portalauditevent',),
        ),
        migrations.CreateModel(
            name='TeacherPortalAuditEvent',
            fields=[
            ],
            options={
                'verbose_name': 'teacher audit event',
                'verbose_name_plural': 'teacher audit events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.portalauditevent',),
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ('-date', 'course__code', 'student__full_name'), 'verbose_name': 'student attendance record', 'verbose_name_plural': 'student attendance records'},
        ),
        migrations.CreateModel(
            name='TeacherAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendance_markings', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', 'teacher__full_name'),
                'indexes': [models.Index(fields=['date', 'status'], name='teacher_attendance_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_attendance_date')],
            },
        ),
    ]
