# Generated by Django 5.2.17 on 2026-09-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_studentportalauditevent_teacherportalauditevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorPortalAuditEvent',
            fields=[
            ],
            options={
                'verbose_name': 'administrator audit event',
                'verbose_name_plural': 'administrator audit events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.portalauditevent',),
        ),
    ]
