# Generated by Django 5.2.17 on 2026-09-28 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_keycloak_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTPDeliveryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_started_at', models.DateTimeField()),
                ('last_requested_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_otp_delivery_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
