# Generated by Django 5.2.17 on 2026-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_smsotpdeliverylimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsotpdeliverylimit',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
