# Generated by Django 5.2.17 on 2026-09-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_smsotpdeliverylimit_verification_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRequestThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['window_started_at'], name='public_throttle_window_idx')],
                'constraints': [models.UniqueConstraint(fields=('purpose', 'fingerprint'), name='unique_public_throttle_bucket')],
            },
        ),
    ]
